### PR TITLE
Enable setting datacenter to EU

### PR DESCRIPTION
**Pull request by srthurman**
Per this section: https://cl.ly/0G2w3N0q3l1X
Of this doc: https://www.appboy.com/documentation/FAQs/#im-using-the-eu-data-center-what-do-i-need-to-do-differently

This should allow a user to properly route their data when they have chosen the EU datacenter.

### CODE REVIEW

**Review by ccnixon — APPROVED** [review]
Don't forget a release commit :)

**Comment by srthurman** [comment]
@ccnixon Is the failure on my "release commit" anything to worry about?

**Comment by ccnixon** [comment]
Hey @srthurman - it looks like it's just an issue with sauce labs, our browser tester. I'll try rebuilding.

I also think this is worth bumping to 1.3.0.

**Comment by srthurman** [comment]
@ccnixon done on the version update!

**Pull request merged**
