### PR TITLE
adding custom user attributes and group functionality

### PR DESCRIPTION
**Pull request by aloisbarreras**

### CODE REVIEW

**Comment by aloisbarreras** [comment]
hello @anoonan !

I added some extra functionality to this that is available on the server side integration. I actually adapted a lot of this code from that integration, so hopefully it looks good.

However, I cannot seem to get 2 of the tests to pass. They are giving this error.

```
Expected "stub" to be called with "[
	  {
	    "email": "gilfoyle@piedpiper.com",
	    "plan": "premium",
	    "logins": 5,
	    "gender": "male",
	    "first_name": "Gilfoyle",
	    "dob": "1992-02-14",
	    "home_city": "San Francisco",
	    "country": "USA",
	    "external_id": "userId"
	  }
	]", 
	 but it was called with "[
	  {
	    "email": "gilfoyle@piedpiper.com",
	    "plan": "premium",
	    "logins": 5,
	    "gender": "male",
	    "first_name": "Gilfoyle",
	    "dob": "1992-02-14",
	    "home_city": "San Francisco",
	    "country": "USA",
	    "external_id": "userId"
	  }
	]"
```

```
Expected "stub" to be called with "[
	  "507f1f77bcf86cd799439011",
	  19,
	  "USD",
	  1,
	  {
	    "order_id": "50314b8e9bcf000000000000",
	    "checkout_id": "fksdjfsdjfisjf9sdfjsd9f"
	  }
	]", 
	 but it was called with "[
	  "507f1f77bcf86cd799439011",
	  19,
	  "USD",
	  1,
	  {
	    "order_id": "50314b8e9bcf000000000000",
	    "checkout_id": "fksdjfsdjfisjf9sdfjsd9f"
	  }
	]"
```

They look the same to me, so I might have been staring at this too long and I'm going crazy :) or there's a weird quirk I'm missing about the integration tester.

Any help would be much appreciated! I would love to get this merged in.

**Comment by anoonan** [comment]
hey @aloisbarreras, thanks for the PR! 

We are actually routing data sent from the client through our Appboy server side integration as well, so this is all handled there for data sent from the server or the client. You can see that here: https://github.com/segment-integrations/integration-appboy/blob/master/lib/index.js#L16 which is why we didn't add this to the client side integration :)

Let me know if you have any other questions! If not, we'll close this out.

**Comment by aloisbarreras** [comment]
@anoonan ah okay. I always thought that it was either/or with client side vs server where if you had the analytics.js library, the server side integration would not be called. So does specifying 'client' in the channels allow it to be sent to the 3rd party integration for both platforms?

And if you don't mind me asking more questions, how do you prevent duplicate events being called? Do you just make sure in this case to not have overlapping logic between the integrations for the 2 platforms?

Thanks for the help!

**Comment by anoonan** [comment]
hey @aloisbarreras, correct. Because client is specified in the server side integration, data from the client will also be routed through the server side integration and sent to Appboy along with data from the server.

In terms of your second question, data from the client will be routed through this integration as well the server side integration, there isn't a de-duping step there. If we added analytics handling to the client side integration, then we'd remove `client` from `.channels()` on the server side integration to prevent duplicate data. 

The main reason for a client side integration is so that customers have the ability to make use of in-app messaging and push notifications in Appboy. 

I'm going to close this out for now but let me know if you have any other questions!

**Pull request closed without merging**
